### PR TITLE
Simplified deps

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge/core can I ignore the linter warning?

**Comment by hmaarrfk** [comment]
lets try a different syntax

**Comment by hmaarrfk** [comment]
If the linter complains, you can't use "automerge" so your quality of life goes down.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Pull request merged**
