### PR TITLE
[ci skip] [skip ci] [cf admin skip] ***NO_CI*** Fix duplicate keys

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

The file had duplicate keys, which is fixed in this PR.

### CODE REVIEW

**Comment by BastianZim** [comment]
The build fails here but not due to the PR. Unfortunately, I don't know enough about the build to fix it but this is CI skip so it could still be merged.

**Comment by looooo** [comment]
thanks for working on this. I guess the last build is quite old, so probably some libraries are missing to build this.
I would prefer to resolving the issues before merging this PR.
win:
```

%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(776): warning C4244: '=': conversion from 'Window' to 'unsigned long', possible loss of data
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(983): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1129): error C3861: 'ntohl': identifier not found
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1476): error C2079: 'short_wait' uses undefined struct 'SPW_InputXPending::timeval'
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1478): error C2065: 'fd_set': undeclared identifier
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1478): error C2146: syntax error: missing ';' before identifier 'Xfds'
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1478): error C2065: 'Xfds': undeclared identifier
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1485): error C3861: 'XPending': identifier not found
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1502): error C2065: 'Xfds': undeclared identifier
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1502): error C3861: 'FD_ZERO': identifier not found
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1503): error C2065: 'Xfds': undeclared identifier
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1503): error C3861: 'FD_SET': identifier not found
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1505): error C2065: 'Xfds': undeclared identifier
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1505): error C3861: 'select': identifier not found
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1509): error C3861: 'XPending': identifier not found
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1897): error C3861: 'XPending': identifier not found
%SRC_DIR%\build\src\Inventor\Qt\devices\spwinput_x11.cpp(1899): error C3861: 'XPeekEvent': identifier not found
[44/92] Building CXX object src\CMakeFiles\SoQt.dir\Inventor\Qt\editors\SoQtMaterialEditor.cpp.obj
```

osx:
```

              ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1509:15: error: use of undeclared identifier 'XPending'
  numevents = XPending (display);
              ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1678:11: error: use of undeclared identifier 'XNextEvent'
          XNextEvent (ds->display, ds->xevent);         /* get an event */
          ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1712:7: error: use of undeclared identifier 'XPutBackEvent'
      XPutBackEvent(ds->display, ds->xevent);
      ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1897:11: error: use of undeclared identifier 'XPending'
      if (XPending (ds->display) > 0)
          ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1899:11: error: use of undeclared identifier 'XPeekEvent'
          XPeekEvent (ds->display, ds->xevent);         /* look at an event */
          ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1904:15: error: use of undeclared identifier 'XNextEvent'
              XNextEvent (ds->display, &throw_away);   /* remove the event */
              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

osx-arm64:
```

  (void)XInternAtom (display, "WM_PROTOCOLS", False);
        ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:912:9: error: use of undeclared identifier 'XInternAtom'
  (void)XInternAtom (display, "WM_DELETE_WINDOW", False);
        ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1485:15: error: use of undeclared identifier 'XPending'
  numevents = XPending (display);
              ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1509:15: error: use of undeclared identifier 'XPending'
  numevents = XPending (display);
              ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1678:11: error: use of undeclared identifier 'XNextEvent'
          XNextEvent (ds->display, ds->xevent);         /* get an event */
          ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1712:7: error: use of undeclared identifier 'XPutBackEvent'
      XPutBackEvent(ds->display, ds->xevent);
      ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1897:11: error: use of undeclared identifier 'XPending'
      if (XPending (ds->display) > 0)
          ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1899:11: error: use of undeclared identifier 'XPeekEvent'
          XPeekEvent (ds->display, ds->xevent);         /* look at an event */
          ^
$SRC_DIR/build/src/Inventor/Qt/devices/spwinput_x11.cpp:1904:15: error: use of undeclared identifier 'XNextEvent'
              XNextEvent (ds->display, &throw_away);   /* remove the event */
              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by looooo** [comment]
Maybe this helps:https://conda-forge.org/docs/maintainer/knowledge_base.html#core-dependency-tree-packages-cdts

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@conda-forge/core has there anything changed regarding x11 dependency? Windows and osx is failing here because of some undeclared identifiers. The last successful build was in May 1, 2022. After that the recipe didn't change.

**Comment by looooo** [comment]
should be included with: https://github.com/conda-forge/soqt-feedstock/pull/18

**Pull request closed without merging**
