### PR TITLE
Qt main

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
```
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lOpenGL
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lGLX
```

@conda-forge/qt-main  I am trying to update this recipe to qt-main and seeing this error. Any hints what I can do about it?

**Comment by ccordoba12** [comment]
I think you need to add new CDT's for this to work. Please take a look at the Qt-main recipe for that:

https://github.com/conda-forge/qt-main-feedstock/blob/main/recipe/meta.yaml

**Comment by looooo** [comment]
@ccordoba12 thanks, do I need to build on centos7? Maybe best to wait for the migration.

**Comment by ccordoba12** [comment]
Yes, Qt-main now depends on CentOS 7.

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@ccordoba12 ok, I figured it out how to make it work. Actually the cdt's from the Conda-forge docs[1] are sufficient in this case. Does it make sense to merge this right now? Is qt-main finished? Is a package for linux_ppc64le planned?

[1] https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl

**Comment by ccordoba12** [comment]
> Does it make sense to merge this right now?

I'm not really sure. @hmaarrfk, what do you say?

> Is a package for linux_ppc64le planned?

No, so please disable that slot.

**Comment by hmaarrfk** [comment]
I guess. Honestly, I'm not sure who uses qt-webengine. But that one still isn't migrated to icu70 which may cause problems in certain environments. Might as well try.

**Comment by ccordoba12** [comment]
> Honestly, I'm not sure who uses qt-webengine

Spyder is the only one I'm sure about.

**Comment by looooo** [comment]
> I guess. Honestly, I'm not sure who uses qt-webengine. But that one still isn't migrated to icu70 which may cause problems in certain environments. Might as well try.

>Spyder is the only one I'm sure about.

pyside2 and FreeCAD are another two packages depending on qt-webengine.

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@conda-forge-admin, please restart ci

**Comment by looooo** [comment]
@conda-forge-admin, please restart ci

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
